# Generated by Django 5.1.4 on 2025-01-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='alice',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='created_by',
        ),
        migrations.AddField(
            model_name='superhero',
            name='first_power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='listed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_superheroes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superhero',
            name='movies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='real_creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='shows',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
