# Generated by Django 5.1.4 on 2025-01-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_remove_superhero_alice_remove_superhero_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='agility',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='combat_skills',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='durability',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='intelligence',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='raw_power',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='wisdom',
            field=models.IntegerField(default=50),
        ),
    ]
