# Generated by Django 5.1.4 on 2025-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_superhero_agility_superhero_combat_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='allies',
            field=models.ManyToManyField(blank=True, related_name='is_ally_of', to='heroes.superhero'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='alter_ego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='comic_series',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='enemies',
            field=models.ManyToManyField(blank=True, related_name='is_enemy_of', to='heroes.superhero'),
        ),
    ]
