# Generated by Django 5.1.4 on 2025-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_superhero_allies_superhero_alter_ego_superhero_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
